// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadDNS returns the embedded CollectionSpec for DNS.
func LoadDNS() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DNSBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load DNS: %w", err)
	}

	return spec, err
}

// LoadDNSObjects loads DNS and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DNSObjects
//	*DNSPrograms
//	*DNSMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDNSObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDNS()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DNSSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DNSSpecs struct {
	DNSProgramSpecs
	DNSMapSpecs
}

// DNSSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DNSProgramSpecs struct {
	HandleDnsTc *ebpf.ProgramSpec `ebpf:"handle_dns_tc"`
}

// DNSMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DNSMapSpecs struct {
	DnsEvents *ebpf.MapSpec `ebpf:"dns_events"`
}

// DNSObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDNSObjects or ebpf.CollectionSpec.LoadAndAssign.
type DNSObjects struct {
	DNSPrograms
	DNSMaps
}

func (o *DNSObjects) Close() error {
	return _DNSClose(
		&o.DNSPrograms,
		&o.DNSMaps,
	)
}

// DNSMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDNSObjects or ebpf.CollectionSpec.LoadAndAssign.
type DNSMaps struct {
	DnsEvents *ebpf.Map `ebpf:"dns_events"`
}

func (m *DNSMaps) Close() error {
	return _DNSClose(
		m.DnsEvents,
	)
}

// DNSPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDNSObjects or ebpf.CollectionSpec.LoadAndAssign.
type DNSPrograms struct {
	HandleDnsTc *ebpf.Program `ebpf:"handle_dns_tc"`
}

func (p *DNSPrograms) Close() error {
	return _DNSClose(
		p.HandleDnsTc,
	)
}

func _DNSClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dns_bpfel.o
var _DNSBytes []byte
